open-zaak/open-notificaties

AUTHORS
README.rst
deployment/appliance/.gitignore
deployment/appliance/README.rst
deployment/appliance/create-container.sh
deployment/appliance/debian-config/preseed.cfg
deployment/appliance/export-ovf.sh
deployment/single-server/vars/open-notificaties.example.yml
docs/introduction/index.rst
docs/introduction/team.rst
package-lock.json
package.json

Added credits, appliance docs and scripts and RTD badge.

---

docker-compose.yml

https://github.com/open-zaak/open-zaak/issues/541

Fixes #541 -- added redis to docker-compose

---

bin/docker_start.sh
docker-compose.yml
src/nrc/conf/includes/base.py
src/nrc/conf/production.py

Same fix as https://github.com/open-zaak/open-zaak/commit/22533f7be0d2a7d0e469f30fb22c54514dd12b85

Fix settings/config for hosting on a subpath

---

src/nrc/api/validators.py

Allow for 401 code when verifying callback URL authentication

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package.json
src/nrc/__init__.py

~~#27 needs to go in too~~
Version bump and changelog for bugfix release 1.1.1

1.1.1 release

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package.json
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/test-tools.in
src/nrc/__init__.py

Release 1.1.2

---

docs/installation/index.rst

fixes: https://github.com/open-zaak/open-zaak/issues/721

:memo: Remove raven test command from post install docs

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/base.py
src/nrc/conf/includes/environ.py

In the wake of https://github.com/open-zaak/open-zaak/security/advisories/GHSA-chhr-gxrg-64x7 
Practical exploits were not found, and even if they existed the impact on Open Notificaties is extremely limited since notifications don't contain actual data, but just the notice that some resource changed.

Made CORS configuration opt-in

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

This includes updated support for Azure AD.

Bump django-auth-adfs(-db) to latest versions

---

CHANGELOG.rst
Dockerfile

to ensure that containers can be run as non-root users

:whale: Fixes #869 -- drop privileges in the application container

---

docs/manual/index.rst
docs/manual/oidc.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/accounts/tests/test_oidc.py
src/nrc/conf/ci.py
src/nrc/conf/dev.py
src/nrc/conf/includes/base.py
src/nrc/fixtures/default_admin_index.json
src/nrc/sass/admin/_app_overrides.scss
src/nrc/templates/admin/login.html
src/nrc/urls.py

fixes: https://github.com/open-zaak/open-zaak/issues/1034

OpenID Connect for admin

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/api/tests/test_notificatie.py

Ensure kenmerk values in notifications can be empty

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes open-zaak/open-zaak#1136
**Changes**
Bumped to latest Django security release

:arrow_up: [open-zaak/open-zaak#1136] -- Bump to Django 3.2.13

---

src/nrc/datamodel/admin.py
src/nrc/datamodel/admin_filters.py

Fixes: https://github.com/open-zaak/open-zaak/issues/1133
Changes:
* Fixed not functioning search in `NotificatieAdmin`
* Added several list display fields to `NotificatieAdmin`
* Added several filters to `NotificatieAdmin`

:lipstick: [#1133] Improvements for notificaties admin

---

docs/manual/subscriptions.rst

Fixes open-zaak/open-zaak#1134
Changes:
* Describe in documentation how to add filters to subscriptions

:memo: [open-zaak/open-zaak#1134] Describe subscription filters in docs

---

docs/delivery_guarantees.rst
docs/index.rst

Related to https://github.com/open-zaak/open-zaak/issues/1151

Robustness documentation

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package-lock.json
package.json
src/nrc/__init__.py

Prepare release 1.4.0

---

src/nrc/conf/includes/base.py
src/nrc/tests/test_oidc_middleware.py

Fixes #74
Thanks for discovering and reporting this @damm89!

Fix broken OIDC session refresh

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.in
requirements/dev.txt

:heavy_plus_sign: [#78] Add missing dependency bleach

---

README.rst
docs/api/index.rst
docs/index.rst
docs/introduction/architecture.rst
docs/introduction/index.rst
docs/introduction/team.rst
publiccode.yaml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/templates/master.html

Upgrade mozilla-oidc-db

---

src/nrc/api/tasks.py
src/nrc/api/tests/test_tasks.py

Add try on NotificatieResponse create + test

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/base.py

add django-log-outgoing-requests

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/dev.py
src/nrc/conf/includes/base.py

Reverts open-zaak/open-notificaties#97

Revert "Issue/add elastic apm support"

---

.github/workflows/ci.yml
Dockerfile

fixes https://github.com/open-zaak/open-zaak/issues/1502

add trivy image scaner to CI

---

.github/workflows/ci.yml

Fixes https://github.com/open-zaak/open-zaak/issues/1518

use tar archive for Trivy

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

:arrow_up: [#119] bump commonground-api-common to 1.13.0

---

.github/workflows/ci.yml
docker-compose.yml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/accounts/management/commands/createinitialsuperuser.py
src/nrc/conf/includes/base.py
src/nrc/tests/test_handle_auth_notifications.py

Upgrade to Django 4.2

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/base.py
src/nrc/tests/test_ref_scopes.py

fix #80 (django_markup part)
Depends on https://github.com/maykinmedia/commonground-api-common/pull/28

deduplicate scopes in the view

---

src/nrc/conf/dev.py
src/nrc/conf/includes/base.py

fixes: #107 
Doesn't really do anything. Small changes to make settings the same as OpenZaak

:wrench:[#107] clean up environment settings

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

:heavy_plus_sign: [#159] add open-api-framework

---

docs/api/index.rst
docs/conf.py
docs/index.rst
docs/installation/configuration/opennotifs_config.rst
docs/introduction/architecture.rst
docs/introduction/index.rst
docs/introduction/team.rst

DH taiga 268
closes https://github.com/open-zaak/open-notificaties/issues/142

:memo: Add missing steps to docs to configure consumers

---

src/nrc/sass/admin/_admin_theme.scss

fixes #150 (Open Notificaties API)

:lipstick: [#150] fix help-text icon layout in the admin

---

src/nrc/conf/includes/base.py

I was a bit too quick to merge the previous PR :sweat_smile:

:wrench: Remove unnecessary settings

---

.github/workflows/generate-postman-collection.yml
.github/workflows/generate-sdks.yml
.github/workflows/lint-oas.yml
src/nrc/conf/includes/api.py
src/nrc/utils/oas_extensions/hyperlink_identity.py
src/openapi.yaml

fixes https://github.com/open-zaak/open-zaak/issues/1708 (ON part)

:construction_worker: add OAS checks as gh actions

---

src/nrc/api/tests/test_notificatie.py
src/nrc/datamodel/models.py

fixes #171 (Notification part)

fix filtering objects notifications

---

Dockerfile
bin/celery_worker.sh
bin/check_celery_worker_liveness.py
docker-compose.yml
src/nrc/celery.py

Fixes open-zaak/open-zaak#1727 partially

:stethoscope: [open-zaak/open-zaak#1727] Celery healthchecks

---

Dockerfile
package-lock.json

Fixes #176 
Changes
Updated setuptools version is in Dockerfile
fixed npm vulnerabilities

:arrow_up: [#50] updated setuptools in Dockerfile, fixed npm vulnerabilities

---

docs/installation/configuration/opennotifs_config_cli.rst
src/nrc/conf/includes/base.py
src/nrc/tests/commands/test_setup_configuration.py

fixes https://github.com/maykinmedia/django-setup-configuration/issues/10 (ON part)

disable config steps by default

---

.bumpversion.cfg
.github/workflows/ci.yml
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package.json
src/nrc/__init__.py

Fixes https://github.com/maykinmedia/open-api-framework/issues/80 (open-notificaties part)

:memo:release 1.7.1

---

CHANGELOG.rst
docs/installation/configuration/opennotifs_config.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/test-tools.in
requirements/testing.in
src/nrc/api/admin.py
src/nrc/api/tests/test_abonnement.py
src/nrc/api/tests/test_kanaal.py
src/nrc/api/tests/test_notificatie.py
src/nrc/api/tests/test_validation.py
src/nrc/conf/includes/base.py
src/nrc/config/authorization.py
src/nrc/datamodel/management/commands/migrate_domains.py
src/nrc/fixtures/default_admin_index.json
src/nrc/tests/commands/test_setup_configuration.py
src/nrc/tests/config/test_authorization_configuration.py
src/nrc/tests/test_handle_auth_notifications.py

Fixes the open-notificaties part of https://github.com/maykinmedia/open-api-framework/issues/66

[#66] update zgw consumers

---

docker/setup_configuration/data.yaml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/base.py

Closes #199 
Based on https://github.com/open-zaak/open-notificaties/pull/201, so that should be merged first

:sparkles: [#199] Add ConfigurationStep for Admin OIDC login

---

docker/setup_configuration/data.yaml
src/nrc/api/tests/test_notificatie.py
src/nrc/conf/includes/base.py
src/nrc/setup_configuration/abonnementen.py
src/nrc/setup_configuration/kanalen.py
src/nrc/setup_configuration/models.py
src/nrc/tests/setup_configuration/files/setup_config_abonnementen_config.yaml
src/nrc/tests/setup_configuration/files/setup_config_abonnementen_empty_kanalen.yaml
src/nrc/tests/setup_configuration/files/setup_config_kanalen_config.yaml
src/nrc/tests/setup_configuration/test_abonnementen_configuration.py
src/nrc/tests/setup_configuration/test_kanalen_configuration.py

:sparkles: [#202] Add ConfigurationStep for Kanalen and Abonnementen

---

docker-compose.yml
docker/setup_configuration/data.yaml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/base.py
src/nrc/datamodel/tests/factories.py

 ✨ [#203] Add config steps for notification settings

---

.github/workflows/ci.yml

Closes maykinmedia/open-api-framework#92 partially

:construction_worker: [maykinmedia/open-api-framework#92] Fix docker latest tag publish

---

.bumpversion.cfg
.github/ISSUE_TEMPLATE/prepare-release.md
bin/bump-my-version.sh
docs/installation/configuration/opennotifs_config.rst
requirements/dev.in
requirements/dev.txt

and add wrapper script to easily bump versions

:heavy_plus_sign: Add bump-my-version to dev dependencies

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/requirements.txt
deployment/single-server/open-notificaties.yml
package-lock.json
package.json
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/__init__.py

:bookmark: Release 1.8.2

---

docs/api/experimental.rst
docs/api/index.rst

Closes #239 
**Changes**
Added experimental.rst, documenting the experimental features found in Kanaal.
**Checklist**

:memo: [#239] document experimental features

---

requirements/dev.txt

**Changes**
* Upgrade dev dependency h11 to 0.16.0 to fix security issue
**Checklist**

:arrow_up: [#268] Upgrade dev dependency h11 to 0.16.0 to fix security issue

---

docker-compose.yml
docs/installation/configuration/env_config.rst
src/nrc/celery.py
src/nrc/conf/includes/base.py

Closes #240 
Related PR for helm-chart: https://github.com/maykinmedia/charts/pull/212

:sparkles: [#240] Add result_expires Celery envvar

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package-lock.json
package.json
publiccode.yaml
src/nrc/__init__.py
src/nrc/conf/locale/nl/LC_MESSAGES/django.po

Closes #268
**Changes**
* Release version 1.9.0
**Checklist**

:bookmark: [#268] Release version 1.9.0

---

.git-blame-ignore-revs
.pre-commit-config.yaml
README.rst
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/test-tools.in
ruff.toml
setup.cfg
src/nrc/accounts/management/commands/createinitialsuperuser.py
src/nrc/accounts/tests/test_createinitialsuperuser.py
src/nrc/api/admin.py
src/nrc/api/serializers.py
src/nrc/api/tasks.py
src/nrc/conf/dev.py
src/nrc/datamodel/admin.py
src/nrc/tests/test_self_signed_certificates.py
src/nrc/utils/hooks.py

Fixes #[maykinmedia/open-api-framework#133]
Workflow: https://github.com/maykinmedia/open-api-workflows/pull/23

:art: [maykinmedia/open-api-framework#133] Refactor code with ruff

---

ruff.toml

:rotating_light: #278 Ban stdlib logging imports, enforce structlog usage

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Closes maykinmedia/open-api-framework#139
**Changes**
[Describe the changes here]
**Checklist**

:wrench: maykinmedia/open-api-framework#139 Integrate django-upgrade-check

---

CHANGELOG.rst
README.rst
deployment/requirements.txt
deployment/single-server/open-notificaties.yml
docs/conf.py
package-lock.json
package.json
publiccode.yaml
pyproject.toml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/__init__.py
src/nrc/conf/locale/nl/LC_MESSAGES/django.po

:bookmark: [#300] release 1.11.0

---

docs/delivery_guarantees.rst

Closes #290 
**Changes**
update documentation so the autoretry explanation and configuration is up to date.
**Checklist**

:memo: [#290] update delivery guarantees docs

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Closes maykinmedia/open-api-framework#172
**Changes**
[Describe the changes here]
**Checklist**

⬆️ [maykinmedia/open-api-framework#172] Upgrade zgw-consumers to 1.0.0

---

bin/docker_start.sh

Closes maykinmedia/open-api-framework#85
**Changes**
- set processes to 4 and threads to 1
**Checklist**

:sparkles: [maykinmedia/open-api-framework#85] Increase uwsgi and celery worker numbers
