open-zaak/open-notificaties

docs/installation/deployment/single_server.rst

because sites framework is not in installed apps

Removed Websites configuration from installation docs

---

.travis.yml
docs/installation/configuration.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/test-tools.in
setup.cfg
src/nrc/accounts/migrations/0003_add_adfs_admin_index.py
src/nrc/api/tests/test_abonnement.py
src/nrc/conf/ci.py
src/nrc/tests/commands/test_setup_configuration.py

- Open Zaak documentation URL changed (was picked up by CI in #25 )
- `ref.tst.vng.cloud` no longer exists, causing a test to fail. This test shouldn't do real HTTP calls anyway, so added request mocking
- bumped isort & black versions, applied them and pinned CI on the versions specified in `requirements/ci.txt`

Fix some quality-of-life problems

---

src/nrc/conf/production.py

Fixes open-zaak/open-zaak#741
**Changes**
* Only prefix `subpath` if it's longer than `/`

Build correct STATIC_URL and MEDIA_URL

---

deployment/single-server/README.md

Instead of providing a short summary with instructions, the README
now refers to the documentation on readthedocs. The target users
of the code itself is now mentioned clearly.

Fixes open-zaak/open-zaak#717 -- rewrite single-server README

---

bin/celery_worker.sh
bin/docker_start.sh

Before this patch, uwsgi was not running as PID, but the docker_start
script got PID 1. This means that when the container runtime signals
to terminate the container, the signal was not actually passed down.
Container runtimes then usually follow that up with a SIGKILL (after
the SIGTERM), after a grace period.
Container restarts should be near-instant after this fix, because the
SIGTERM will be honored instead of having to wait the grace period and
have the container killed by SIGKILL.

Ensure uwsgi becomes PID 1

---

Dockerfile
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Swapping to debian-slim no longer provided us with a `/etc/mime.types` file, which is used by uwsgi.

Fix 1.2.2 regression

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

* replaced vng-api-common with commonground-api-common at same version
* bumped certifi
* bumped django to latest patch release
* bumped pytz to latest version (otherwise makemigrations picks up a new migration)

Replace vng api common and bump some dependencies

---

Dockerfile
bin/celery_beat.sh
docker-compose.yml
docs/installation/configuration/env_config.md
src/nrc/api/tasks.py
src/nrc/conf/includes/base.py
src/nrc/datamodel/management/commands/clean_old_notifications.py
src/nrc/tests/commands/test_clean_old_notifications.py

#100 After several discussions we decided that the best way to deal with this problem in the long term was to create a Django command to remove old notifications. The default value is 30 days, which considerably increases query execution speed.

Creation of a command to delete outdated notifications

---

Dockerfile

:bug: [#120] bring netcat back

---

docs/installation/configuration/env_config.md
docs/installation/configuration/opennotifs_config_cli.rst
src/nrc/api/tasks.py
src/nrc/api/tests/test_notificatie.py
src/nrc/conf/includes/base.py
src/nrc/config/notification_retry.py
src/nrc/tests/commands/test_setup_configuration.py
src/nrc/tests/config/test_notification_retry_configuration.py

Fixes https://github.com/open-zaak/open-zaak/issues/1203
Replacement for https://github.com/open-zaak/open-notificaties/pull/70
Changes:
* use admin configurable parameters from `NotificationsConfig` for retry behavior
* keep environment variables and use them to setup `NotificationsConfig` with `setup_configuration`
* update documentation

 ✨ [open-zaak/open-zaak#1203] Setup configuration for retry variables 

---

CHANGELOG.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/base.py

issue: open-zaak/open-zaak#1629
Requires https://github.com/maykinmedia/open-api-framework/pull/35 to be merged and released

 🔧 [open-zaak/open-zaak#1629] Refactor settings module

---

.readthedocs.yaml

The docs build was failing because of this

:wrench: Add missing readthedocs config

---

src/nrc/datamodel/admin.py
src/nrc/tests/admin/test_abonnement.py

Fixes https://github.com/open-zaak/open-notificaties/issues/157
this would previously result in a large list if a lot of notifications were sent, making deleting the Abonnement annoying

:zap: [#157] Hide NotificatieResponses when deleting Abonnement

---

.github/workflows/ci.yml
bin/generate_envvar_docs.sh
docs/installation/configuration/env_config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/dev.py
src/nrc/conf/includes/base.py
src/nrc/templates/open_api_framework/env_config.rst

Fixes https://github.com/open-zaak/open-zaak/issues/1649 partially
**Changes**
* Document the envvars
* Add CI job to check if envvar docs were updated

📝 [open-zaak/open-zaak#1649] Document envvars

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package-lock.json
package.json
src/nrc/__init__.py

fixes https://github.com/maykinmedia/objects-api/issues/436 (ON part)

:bookmark: release 1.7.0

---

src/nrc/accounts/tests/test_2fa.py
src/nrc/accounts/views.py
src/nrc/urls.py

fixes maykinmedia/open-api-framework#40 partially

:wrench: Always use requests.hostname for 2FA app title

---

src/nrc/datamodel/admin.py
src/nrc/fixtures/default_admin_index.json
src/nrc/templates/admin/datamodel/abonnement/change_list.html
src/nrc/tests/admin/test_abonnement.py

fixes #108 
Changes:
* Add django-lor config and logs to admin index fixture
* Admin action to check Abonnement callback status with a custom button to run this action for all Abonnementen

 ✨ [#108] Admin action to check Abonnement callback status

---

docs/delivery_guarantees.rst
docs/installation/configuration/opennotifs_config_cli.rst

related to: https://github.com/maykinmedia/objects-api/issues/403
this still used outdated information, the envvars are now only used by setup configuration and the config can be done via the admin

:memo: Update delivery guarantee documentation

---

src/nrc/api/serializers.py
src/nrc/api/tests/test_kanaal.py
src/nrc/api/viewsets.py
src/nrc/utils/help_text.py
src/openapi.yaml

Closes #207 partially
Related issue #156

✨ [#207] Add experimental PUT and PATCH for Kanaal

---

docs/installation/configuration/env_config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/accounts/tests/test_oidc.py
src/nrc/fixtures/default_admin_index.json

maykinmedia/open-api-framework#46

:arrow_up: update to open-api-framework 0.9.1

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/single-server/open-notificaties.yml
package-lock.json
package.json
src/nrc/__init__.py

:bookmark: Release 1.8.0

---

bin/celery_worker.sh

Done as part of https://github.com/maykinmedia/charts/issues/165

:fire: Remove unused celery command line args

---

src/nrc/sass/admin/_admin_theme.scss

Closes #248 
**Changes**
* Fix broken tooltip helptexts for datetime fields in admin
**Checklist**

:lipstick: [#248] Fix broken tooltip helptexts for datetime fields in admin

---

.github/workflows/oas-check.yml
bin/generate_schema.sh
src/openapi.yaml

to verify that the schema is up to date
Closes maykinmedia/open-api-framework#115 partially
**Changes**
* Always run OAS check
**Checklist**

:construction_worker: [maykinmedia/open-api-framework#115] Always run OAS check

---

docker/setup_configuration/data.yaml
docs/installation/configuration/env_config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/conf/includes/api.py
src/nrc/conf/includes/base.py
src/nrc/fixtures/default_admin_index.json
src/nrc/tests/test_view_config.py
src/nrc/utils/__init__.py

Partially fixed https://github.com/maykinmedia/open-api-framework/issues/59

:sparkles: Remove django.contrib.sites

---

docker/setup_configuration/data.yaml
docs/delivery_guarantees.rst
src/nrc/conf/includes/base.py
src/nrc/setup_configuration/models.py
src/nrc/setup_configuration/steps.py
src/nrc/tests/setup_configuration/files/notifications_config_with_service_identifier.yaml
src/nrc/tests/setup_configuration/files/notifications_config_without_service_identifier.yaml
src/nrc/tests/setup_configuration/test_notification_configuration.py

:bug: [#258] Make notifications_api_service_identifier optional

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/nrc/api/tests/test_notificatie.py

for the configurable base factor for retry settings
Closes #290 
**Changes**
* Upgrade notifications-api-common to 0.8.0
**Checklist**

:arrow_up: Upgrade notifications-api-common to 0.8.0
